// Bulk generate keys handler
async function handleBulkGenKey(interaction) {
  await interaction.deferReply({ ephemeral: true });
  
  const type = interaction.options.getString('type');
  const quantity = interaction.options.getInteger('quantity');
  
  try {
    // Call the API to bulk generate keys
    const response = await axios.post(`${API_URL}/api/licenses/bulk-generate`, {
      type,
      quantity
    }, {
      headers: {
        'Authorization': `Bearer ${process.env.API_TOKEN}`
      }
    });
    
    if (response.data.success) {
      // Create a CSV file with the generated keys
      const keys = response.data.licenses;
      let csvContent = "License Key,Type,Created At\n";
      
      keys.forEach(license => {
        csvContent += `${license.key},${license.type},${new Date(license.createdAt).toISOString()}\n`;
      });
      
      // Create attachment
      const attachment = new AttachmentBuilder(
        Buffer.from(csvContent, 'utf-8'),
        { name: `bulk_keys_${Date.now()}.csv` }
      );
      
      // Create embed
      const embed = new EmbedBuilder()
        .setColor('#00FF00')
        .setTitle('Bulk License Keys Generated')
        .setDescription(`Successfully generated ${keys.length} ${type} license keys.`)
        .addFields(
          { name: 'Type', value: type, inline: true },
          { name: 'Quantity', value: quantity.toString(), inline: true },
          { name: 'Generated By', value: interaction.user.tag, inline: true }
        )
        .setTimestamp();
      
      await interaction.editReply({ 
        embeds: [embed],
        files: [attachment],
        ephemeral: true
      });
      
      // Log to admin channel
      const adminChannel = client.channels.cache.get(process.env.DISCORD_ADMIN_CHANNEL_ID);
      if (adminChannel) {
        adminChannel.send({
          embeds: [
            new EmbedBuilder()
              .setColor('#00FF00')
              .setTitle('Bulk License Keys Generated')
              .setDescription(`${interaction.user.tag} generated ${keys.length} ${type} license keys.`)
              .setTimestamp()
          ]
        });
      }
    } else {
      await interaction.editReply({ 
        content: `Failed to generate keys: ${response.data.message || 'Unknown error'}`,
        ephemeral: true
      });
    }
  } catch (error) {
    console.error('Error generating bulk keys:', error);
    await interaction.editReply({ 
      content: `Error generating bulk keys: ${error.response?.data?.message || error.message || 'Unknown error'}`,
      ephemeral: true
    });
  }
}

// Bulk delete keys handler
async function handleBulkDelete(interaction) {
  await interaction.deferReply({ ephemeral: true });
  
  const status = interaction.options.getString('status');
  const days = interaction.options.getInteger('days');
  
  try {
    // Call the API to bulk delete keys
    const response = await axios.delete(`${API_URL}/api/licenses/bulk-delete`, {
      data: {
        status,
        olderThanDays: days
      },
      headers: {
        'Authorization': `Bearer ${process.env.API_TOKEN}`
      }
    });
    
    if (response.data.success) {
      // Create embed
      const embed = new EmbedBuilder()
        .setColor('#FF0000')
        .setTitle('Bulk License Keys Deleted')
        .setDescription(`Successfully deleted ${response.data.deletedCount} license keys.`)
        .addFields(
          { name: 'Status', value: status, inline: true },
          { name: 'Older Than', value: `${days} days`, inline: true },
          { name: 'Deleted By', value: interaction.user.tag, inline: true }
        )
        .setTimestamp();
      
      await interaction.editReply({ 
        embeds: [embed],
        ephemeral: true
      });
      
      // Log to admin channel
      const adminChannel = client.channels.cache.get(process.env.DISCORD_ADMIN_CHANNEL_ID);
      if (adminChannel) {
        adminChannel.send({
          embeds: [
            new EmbedBuilder()
              .setColor('#FF0000')
              .setTitle('Bulk License Keys Deleted')
              .setDescription(`${interaction.user.tag} deleted ${response.data.deletedCount} ${status} license keys older than ${days} days.`)
              .setTimestamp()
          ]
        });
      }
    } else {
      await interaction.editReply({ 
        content: `Failed to delete keys: ${response.data.message || 'Unknown error'}`,
        ephemeral: true
      });
    }
  } catch (error) {
    console.error('Error deleting bulk keys:', error);
    await interaction.editReply({ 
      content: `Error deleting bulk keys: ${error.response?.data?.message || error.message || 'Unknown error'}`,
      ephemeral: true
    });
  }
}
require('dotenv').config();
const { Client, GatewayIntentBits, Partials, SlashCommandBuilder, REST, Routes, EmbedBuilder, AttachmentBuilder, ActivityType } = require('discord.js');
const axios = require('axios');

const TOKEN = process.env.DISCORD_TOKEN;
const OWNER_ROLE_ID = process.env.DISCORD_OWNER_ROLE_ID;
const GUILD_ID = process.env.DISCORD_GUILD_ID;
const API_URL = process.env.API_URL || 'http://0.0.0.0:3000';

if (!TOKEN) {
  console.error('Missing DISCORD_TOKEN in .env');
  process.exit(1);
}

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMembers
  ],
  partials: [Partials.Channel]
});

function hasOwnerRole(member) {
  if (!OWNER_ROLE_ID) return false;
  return member.roles.cache.has(OWNER_ROLE_ID);
}

// Register slash commands
const commands = [
  new SlashCommandBuilder()
    .setName('bulkgen')
    .setDescription('Bulk generate license keys (owner only)')
    .addStringOption(opt => opt.setName('type').setDescription('License type').setRequired(true))
    .addIntegerOption(opt => opt.setName('quantity').setDescription('How many keys').setRequired(true)),
  new SlashCommandBuilder()
    .setName('bulkdel')
    .setDescription('Bulk delete license keys (owner only)')
    .addStringOption(opt => opt.setName('status').setDescription('License status').setRequired(true))
    .addIntegerOption(opt => opt.setName('days').setDescription('Older than days').setRequired(true)),
].map(c => c.toJSON());

client.once('ready', async () => {
  console.log(`✅ Discord bot logged in as ${client.user.tag}`);
  try {
    const rest = new REST({ version: '10' }).setToken(TOKEN);
    const appId = client.user.id;
    const guildId = GUILD_ID || client.guilds.cache.first()?.id;
    if (!guildId) {
      console.warn('No guild detected; slash commands registration skipped');
    } else {
      await rest.put(Routes.applicationGuildCommands(appId, guildId), { body: commands });
      console.log('✅ Slash commands registered');
    }
  } catch (e) {
    console.error('Error registering slash commands:', e);
  }

  // Presence: show member count and a custom status
  const updatePresence = () => {
    const guild = client.guilds.cache.get(GUILD_ID) || client.guilds.cache.first();
    const memberCount = guild ? guild.memberCount : 0;
    client.user.setPresence({
      activities: [{ name: `Serving ${memberCount} members`, type: ActivityType.Watching }],
      status: 'online'
    });
  };
  updatePresence();
  setInterval(updatePresence, 60 * 1000);
});

client.on('interactionCreate', async (interaction) => {
  if (!interaction.isChatInputCommand()) return;
  const member = await interaction.guild.members.fetch(interaction.user.id);
  if (!hasOwnerRole(member)) {
    return interaction.reply({ content: 'You do not have permission to use this command.', ephemeral: true });
  }

  const API_TOKEN = process.env.API_TOKEN || '';
  const headers = API_TOKEN ? { Authorization: `Bearer ${API_TOKEN}` } : {};

  if (interaction.commandName === 'bulkgen') {
    await interaction.deferReply({ ephemeral: true });
    const type = interaction.options.getString('type');
    const quantity = interaction.options.getInteger('quantity');
    try {
      const response = await axios.post(`${API_URL}/api/licenses/bulk-generate`, { type, quantity }, { headers });
      if (response.data.success) {
        const keys = response.data.licenses || [];
        let csvContent = 'License Key,Type,Created At\n';
        keys.forEach(license => {
          csvContent += `${license.key},${license.type},${new Date(license.createdAt || Date.now()).toISOString()}\n`;
        });
        const attachment = new AttachmentBuilder(Buffer.from(csvContent, 'utf-8'), { name: `bulk_keys_${Date.now()}.csv` });
        const embed = new EmbedBuilder()
          .setColor('#00FF00')
          .setTitle('Bulk License Keys Generated')
          .setDescription(`Successfully generated ${keys.length} ${type} license keys.`)
          .setTimestamp();
        await interaction.editReply({ embeds: [embed], files: [attachment], ephemeral: true });
      } else {
        await interaction.editReply({ content: `Failed to generate keys: ${response.data.message || 'Unknown error'}`, ephemeral: true });
      }
    } catch (error) {
      console.error('Error generating bulk keys:', error);
      await interaction.editReply({ content: `Error generating bulk keys: ${error.response?.data?.message || error.message || 'Unknown error'}`, ephemeral: true });
    }
  }

  if (interaction.commandName === 'bulkdel') {
    await interaction.deferReply({ ephemeral: true });
    const status = interaction.options.getString('status');
    const days = interaction.options.getInteger('days');
    try {
      const response = await axios.delete(`${API_URL}/api/licenses/bulk-delete`, { data: { status, olderThanDays: days }, headers });
      if (response.data.success) {
        const embed = new EmbedBuilder()
          .setColor('#FF0000')
          .setTitle('Bulk License Keys Deleted')
          .setDescription(`Successfully deleted ${response.data.deletedCount} license keys.`)
          .setTimestamp();
        await interaction.editReply({ embeds: [embed], ephemeral: true });
      } else {
        await interaction.editReply({ content: `Failed to delete keys: ${response.data.message || 'Unknown error'}`, ephemeral: true });
      }
    } catch (error) {
      console.error('Error deleting bulk keys:', error);
      await interaction.editReply({ content: `Error deleting bulk keys: ${error.response?.data?.message || error.message || 'Unknown error'}`, ephemeral: true });
    }
  }
});

client.login(TOKEN);
